---
title: "Future Exercise"
---
```{r}
#Install dslabs package

#Load dslabs library
#install.packages("dslabs")
library("dslabs")

#See overview of the gapminder data from dslabs
str(gapminder)

#Get summary of the gapminder data
summary(gapminder)

#Determine data type of gapminder
class(gapminder)

#Assign African countries to africadata, then see overview and summary of subsetted data
africadata = subset(gapminder, continent == "Africa")
str(africadata)
summary(africadata)

#Install and load dplyr package
#install.packages("dplyr")
library("dplyr")

#Select infanty mortality and life expctancy from africadata
africainfantmortal = select(africadata, c('infant_mortality','life_expectancy'))

#Select population and life expectancy from africadata
africapop = select(africadata, c('population','life_expectancy'))

#See overview and summarize selected data from africadata
str(africainfantmortal)
summary(africainfantmortal)
str(africapop)
summary(africapop)

#Install and Load ggplot2 package to make plots
#install.packages("ggplot2")
library("ggplot2")

#Make a plot of life expectancy versus infant mortality
ggplot(data = africainfantmortal, aes(x = infant_mortality, y = life_expectancy)) + geom_point(color = "green") + labs(x = "Infant Mortality", y = "Life Expectancy")

#Make a plot of life expectancy versus population, with population on a log scale
ggplot(data = africapop, aes(x = population, y = life_expectancy)) + geom_point(color = "pink") + scale_x_log10() + labs(x = "Population (log10)", y = "Life Expectancy")

#The reason that we see streaks of data is because of this data being collected over time and there are different years for different countries being sampled.

#Find out which years have missing/NA values
africadata$year[is.na(africadata$infant_mortality)]

#Extract data from the year 2000 from africadata
africa2000 = subset(africadata, year == "2000")
str(africa2000)
summary(africa2000)

#Make Same Plots as Done Before
##Select infanty mortality and life expctancy from africa2000
africainfantmortal2000 = select(africa2000, c('infant_mortality','life_expectancy'))

##Select population and life expectancy from africa2000
africapop2000 = select(africa2000, c('population','life_expectancy'))

##Make a plot of life expectancy versus infant mortality for 2000 Africa Data
ggplot(data = africainfantmortal2000, aes(x = infant_mortality, y = life_expectancy)) + geom_point(color = "dark green") + labs(x = "Infant Mortality", y = "Life Expectancy")


##Make a plot of life expectancy versus population, with population on a log scale for 2000 Africa Data
ggplot(data = africapop2000, aes(x = population, y = life_expectancy)) + geom_point(color = "red") + scale_x_log10() + labs(x = "Population (log10)", y = "Life Expectancy")

#Fit a linear model with infant_mortality as the predictor
model_infant = lm(life_expectancy ~ infant_mortality, data = africainfantmortal2000)

#Fit a linear model with population as the predictor
model_pop = lm(life_expectancy ~ population, data = africapop2000)

#Summarize the models
summary(model_infant)
summary(model_pop)

#What we found using this model was that infant mortality is a statistically significant predictor of life expectancy (p-value = 2.826e-08), whereas population is not a statistically significant predictor of life expectancy. This matches with the plots we generated previously, where was saw a strong positive correlation between life expectancy and infant mortality and no correlation between life expectancy and population.
```


# Part2 Addtional data exploration
## This section contributed by LiangLai
```{r}
# Load packages
library(dslabs)
library(tidyverse)

# Add dataset
data(murders)

# Look structure
str(murders)
summary(murders)

# Check missing
colSums(is.na(murders))

# Data processing
# Raw counts of murders are not directly comparable，so we create a murder rate per 100,000 people.
murders2 <- murders %>%
  mutate(
    murder_rate = total / population * 100000
  )
summary(murders2$murder_rate)

# Exploratory
# Distribution of murder rates across states
ggplot(murders2, aes(x = murder_rate)) +
  geom_histogram(bins = 20) +
  labs(
    title = "Distribution of Murder Rates Across US States",
    x = "Murder rate per 100,000 population",
    y = "Number of states"
  )

# The murder rate in most states is relatively low (less than 5 cases per 100,000 people), while in a few states it is much higher, resulting in a right-skewed distribution pattern.

# Comparison of murder rates by region
ggplot(murders2, aes(x = region, y = murder_rate)) +
  geom_boxplot() +
  labs(
    title = "Murder Rates by US Region",
    x = "Region",
    y = "Murder rate per 100,000 population"
  )

# Regionally, the South shows higher median murder rates and greater variability compared with other regions. 

# Linear model 
# we fit a linearregression model with murder rate as the outcome.
model_mur <- lm(murder_rate ~ log(population) + region, data = murders2)

# Display results
summary(model_mur)

# In the result of regression model, it reveals that population size has no significant impact on murder rates (p = 0.976), indicating that state population size is not meaningfully associated with murder rates. Using the Northeast as the reference category, states in the South have significantly higher murder rates, with an average increase of 2.57 murders per 100,000 population compared to Northeast states (p = 0.008). In contrast, differences for North Central (β = 0.34, p = 0.736) and West (β = −0.02, p = 0.987) relative to the Northeast are not statistically significant.
```